.build test config:
  stage: build
  tags:
    - firmware-builder
  rules:
    - if: '$CI_COMMIT_BRANCH == "prplwrt"'
      when: delayed
      start_in: '8 hours'
  image:
    name: python:3.8-slim-buster
  before_script:
    - touch .build_failed

    - apt-get update
    - apt-get install -y file gosu python2.7-minimal pwgen locales build-essential git-core subversion libncurses5-dev gawk unzip signify-openbsd wget curl
    - pip install -r scripts/gitlab/requirements.txt
    - useradd builder

  script:
    - gosu builder mkdir logs

    - export CI_BUILD_CONFIG="$(echo $CI_JOB_NAME | sed 's/build test \(.*\)/\1/')"
    - gosu builder scripts/gen_config.py $CI_BUILD_CONFIG 2>&1 | tee logs/build.log
    - gosu builder echo CONFIG_BUILD_LOG=y >> .config
    - gosu builder make defconfig | tee --append logs/build.log
    - gosu builder make -j $(nproc) 2>&1 | tee --append logs/build.log

    - rm .build_failed

  after_script:
    - test -f .build_failed && scripts/gitlab/prpl-jira.py build_failure

  artifacts:
    expire_in: 1 month
    when: always
    paths:
      - bin
      - logs
  cache:
    key: openwrt-downloads
    paths:
      - dl/
