#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/lighttpd

validate_conf() {
        $PROG -tt -f /webui/etc/lighttpd.conf >/dev/null 2>&1 || {
                echo "validation failed"
                return 1
        }
}

start_service() {
        if !(id lighttpd &>/dev/null); then
                useradd lighttpd
                usermod -a -G lighttpd lighttpd
        fi

        chown -R lighttpd:lighttpd /webui

        validate_conf || exit 1

        procd_open_instance
        procd_set_param command $PROG -D -f /webui/etc/lighttpd.conf
        procd_close_instance
}

reload_service() {
        procd_send_signal lighttpd
}
